project_id = "business-center"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[edge_runtime]
enabled = true
policy = "per_worker"
inspector_port = 8083

[functions.bagelpay-webhook]
verify_jwt = false

[functions.create-recharge-order]
verify_jwt = false

[functions.sso-login]
verify_jwt = false

[functions.client-auth]
verify_jwt = false
